language: minimal

matrix:
  include:
  - os: linux
    env: PYTHON_VERSION="3.5" MAINDEPS="numpy=1.12 gdal=2.2.4 scipy=0.19 pytz" DEPS="dask-core=0.18 toolz=0.9 pandas=0.19 geopandas=0.4.1"
  - os: linux
    env: PYTHON_VERSION="3.6" MAINDEPS="numpy=1.14 gdal=2.2.4 scipy=1.1 pytz" DEPS="dask-core=0.20 toolz=0.10 pandas=0.23 geopandas=0.5"
  - os: linux
    env: PYTHON_VERSION="3.7" MAINDEPS="numpy scipy pytz" DEPS="dask-core gdal=2.* toolz geopandas pyproj>=2"
  - os: linux
    env: PYTHON_VERSION="3.8" MAINDEPS="numpy scipy pytz" DEPS="dask-core gdal=2.* toolz geopandas pyproj>=2"
  - os: osx
    env: PYTHON_VERSION="3.7" MAINDEPS="numpy scipy pytz" DEPS="dask-core gdal=2.* toolz geopandas pyproj>=2"

install:
  - wget https://repo.anaconda.com/pkgs/misc/conda-execs/conda-latest-$TRAVIS_OS_NAME-64.exe -O conda.exe
  - chmod +x conda.exe
  - export CONDA_ALWAYS_YES=1
  - ./conda.exe create --prefix $HOME/miniconda python=$PYTHON_VERSION conda pytest $MAINDEPS
  - ./conda.exe install --prefix $HOME/miniconda --channel conda-forge $DEPS
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - pip install . --no-deps

script:
  - pytest
